### ISSUE TITLE
List existing modules

### ISSUE THREAD

**Issue by andrzej-casper** [odradev/odradev.github.io#16]
By browsing Odra code I discovered there is implementation of Wrapped ERC-20 token :open_mouth: 

It would be nice, if all implemented modules could be mentioned in docs, e.g. at [Modules page](https://odra.dev/docs/basics/modules).

**Comment by kpob** [comment]
All available modules were added to version 0.3.x 
#17 resolves this issue

**Comment by kubaplas** [comment]
#17 was merged
Modules list is available at https://odra.dev/docs/examples/using-odra-modules#available-modules
Thanks @andrzej-casper for pointing this out and thanks @kpob for implementing it :smile:

**Comment by andrzej-casper** [comment]
Thanks, I see list of modules [here](https://odra.dev/docs/examples/using-odra-modules#available-modules).
